name: Model Check

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    # Run once a day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  model-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # GitHub Actions timeout as a safety net

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Run model checking (5 minutes)
      run: |
        echo "Running model-based property testing for 5 minutes..."
        npx tsx src/modelCheck.ts 300000  # 5 minutes in milliseconds
      env:
        NODE_ENV: production

    - name: Run model checking (1000 iterations)
      run: |
        echo "Running model-based property testing for 1000 iterations..."
        MODEL_CHECK_RUNS=1000 npx tsx src/modelCheck.ts
      env:
        NODE_ENV: production